<?php
    $type = $this->getType();
    $qty = $this->getQty();
?>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide">Slide 1</div>
        <div class="swiper-slide">Slide 2</div>
        <div class="swiper-slide">Slide 3</div>
        <div class="swiper-slide">Slide 4</div>
        <div class="swiper-slide">Slide 5</div>
        <div class="swiper-slide">Slide 6</div>
        <div class="swiper-slide">Slide 7</div>
        <div class="swiper-slide">Slide 8</div>
        <div class="swiper-slide">Slide 9</div>
        <div class="swiper-slide">Slide 10</div>
    </div>
    <!-- Add Pagination -->
    <?php if($type != 1):?>
    <div class="swiper-pagination"></div>
    <?php endif;?>
    <!-- Add Arrows -->
    <?php if($type == 4):?>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    <?php endif;?>
</div>
<script>
    jQuery(document).ready(function(){
        var type = <?php echo $this->getType(); ?>;
        switch(type){
            case '1':
                var swiper = new Swiper('.swiper-container');
                break;
            case '2':
                var swiper = new Swiper('.swiper-container', {
                    pagination: '.swiper-pagination',
                    paginationClickable: true
                });
                break;
            case '3':
                var swiper = new Swiper('.swiper-container', {
                    pagination: '.swiper-pagination',
                    paginationClickable: true,
                    direction: 'vertical'
                });
                break;
            default :
                var swiper = new Swiper('.swiper-container', {
                    pagination: '.swiper-pagination',
                    paginationClickable: '.swiper-pagination',
                    nextButton: '.swiper-button-next',
                    prevButton: '.swiper-button-prev',
                    spaceBetween: 30
                });
                break;
        }

    });
</script>
