<?php
    $product = $this->getBestSellerProduct();
$_imgSize = 210;
$start = $this->getStartDate();
$end = $this->getEndDate();
//echo "<pre>";
//print_r($start);
//print_r($product);
?>

<div class="swiper-container swiper-container2">
    <h2>Best Seller Products</h2>
    <div class="swiper-wrapper">
        <?php foreach($product as $val): ?>
            <div class="swiper-slide"><img src="<?php echo $this->helper('catalog/image')->init($val, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"/></div>
        <?php endforeach; ?>
    </div>
</div>

<!-- Initialize Swiper -->
<script>
    var swiper2 = new Swiper('.swiper-container2', {
        slidesPerView: 3,
        spaceBetween: 30
    });
</script>

<style>
    .swiper-container2 {
        width: 100%;
        height: 250px;
        border: 1px solid black;
        margin-top: 30px;
    }
</style>