<?php
    $product = $this->getFeaturedProduct();
$_imgSize = 210;
?>
<div class="swiper-container swiper-container1">
    <div class="swiper-wrapper">
        <?php foreach($product as $val): ?>
        <div class="swiper-slide"><img src="<?php echo $this->helper('catalog/image')->init($val, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"/></div>
        <?php endforeach; ?>
    </div>
</div>

<!-- Initialize Swiper -->
<script>
    var swiper1 = new Swiper('.swiper-container1', {
        slidesPerView: 3,
        spaceBetween: 30
    });
</script>

<style>
    .swiper-container1 {
        width: 100%;
        height: 250px;
        border: 1px solid black;
        margin-top: 30px;
    }
</style>